const CHANGE_LOGIN = 'CHANGE_LOGIN';
const FETCH_LOGIN = 'FETCH_LOGIN';
const CHANGE_INPUT_ERROR_MESSAGE = 'CHANGE_INPUT_ERROR_MESSAGE';
const FETCH_SIGNUP = 'FETCH_SIGNUP';

export {CHANGE_LOGIN, FETCH_LOGIN, CHANGE_INPUT_ERROR_MESSAGE, FETCH_SIGNUP};