const CHANGE_LOGIN = 'CHANGE_LOGIN';
const FETCH_LOGIN = 'FETCH_LOGIN';
const CHANGE_INPUT_ERROR_MESSAGE = 'CHANGE_INPUT_ERROR_MESSAGE';
const FETCH_SIGNUP = 'FETCH_SIGNUP';
const START_FETCH = 'START_FETCH';
const END_FETCH = 'END_FETCH';

export {CHANGE_LOGIN, FETCH_LOGIN, CHANGE_INPUT_ERROR_MESSAGE, FETCH_SIGNUP, START_FETCH, END_FETCH};
